1279979 Neutron TypeError when token invalid
When a neutron api-call is made, if the user's token is invalid, the
neutron client will return a type-error because no auth_url has been
provided.

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

This TypeError should really be an
neutronclient.common.exceptions.Unauthorized instead, which will get
percolated up via a password-base authentication failure.

Change-Id: I284e5cdf943fc63faf8509fdbe3caa45179d5f71
Closes-Bug: 1279979